name: run-on-docker
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [0]

    container: cypress/included:10.10.0

    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          cd "db_api_ui" && npm install

      - name: Run Testing
        run: |
          cd "db_api_ui" && npm run runCucumber
        continue-on-error: false

    # steps:
    #   - uses: actions/checkout@v2
    #   # - run: cd "db_api_ui" && npm install && npm run cy:record:parallel:qa --ci-build-id ${{ github.run_id }}
    #   - name: Run Testing
    #     run: cd "db_api_ui" && npm run runCucumber

    #   - name: Run Testing
    #     run: cd "db_api_ui" && npm run generalReport
