name: run-on-docker
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [0]

    container: cypress/included:10.10.0

    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          cd "db_api_ui" && npm install

      - name: Remove files
        run: |
          cd "db_api_ui" && npm run removeFile
        continue-on-error: false

      - name: Run Testing
        run: |
          cd "db_api_ui" && npm run runCucumber
        continue-on-error: false

      - name: Generate reports
        run: cd "db_api_ui" && npm run generalReport
        continue-on-error: false

      - name: Zip folder
        run: cd "db_api_ui" && npm run zipFolder
        continue-on-error: false

      - name: Send email
        run: cd "db_api_ui" && npm run sendEmail
        continue-on-error: false
